on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"