on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 

- name: Build Docker image
  run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:master-latest .

- name: Log in to Docker Hub
  run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

- name: Push Docker image
  run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:master-latest
