on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master
      - feature
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: .